version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-tut4-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jyh66dqf3rdq"
s3_prefix = "aws-tut4-1"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

